services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    env_file:
      - .env
    environment:
      # --- Redis externo del proyecto "triexpert" ---
      REDIS_HOST: triexpert_redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "evolution"             # cámbiala luego por una fuerte
      REDIS_URI: "redis://default:evolution@triexpert_redis:6379"
      # ----------------------------------------------
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - easypanel-triexpert   # red compartida donde vive tu Redis
      - evolution-net         # opcional: tu red local del proyecto

  postgres:
    container_name: postgres
    image: postgres:15
    command: ["postgres", "-c", "max_connections=200", "-c", "listen_addresses=*"]
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: evolution
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d evolution -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - evolution-net         # no necesita ver Redis, pero puedes añadir overlay si quieres

volumes:
  evolution_instances:
  postgres_data:

networks:
  # red local del proyecto (si ya la tenías)
  evolution-net:
    name: triexpert_evolution_default
    driver: bridge
  # *** ESTA ES LA CLAVE ***
  easypanel-triexpert:
    external: true
